Build fails due to possible circular inheritance
Working on debugging this error

treasure.h:11:25: error: base class has incomplete type
class Treasure : public Game {